[
    {
        "document": {
            "document_type": "GST Tax Invoice",
            "document_title": "GST TAX INVOICE",
            "invoice_number": "00016/26-27",
            "invoice_date": "2026-04-06",
            "invoice_reference_number": "FILE NO. 4600009327-3 BLR",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "INR",
            "place_of_supply": "Maharashtra",
            "supply_type": "Services",
            "reverse_charge": "No"
        },
        "supplier": {
            "name": "KUNAL LOGISTICS",
            "legal_name": "KUNAL LOGISTICS",
            "trade_name": "GOLWALA GROUP",
            "vendor_code": "",
            "address": "Plot No. 860, Steel Market, Next to Maruti Chamber, Kalamboli Navi Mumbai",
            "city": "Navi Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "",
            "gstin": "27AAHFK5419N1ZV",
            "pan": "AAHFK5419N",
            "cin": "",
            "tan": "",
            "email": "kunallogistics@gmail.com",
            "phone": "27424028",
            "website": "www.golwala.in"
        },
        "customer": {
            "name": "THE SUPREME INDUSTRIES LTD (KHOPOLI)",
            "legal_name": "THE SUPREME INDUSTRIES LTD",
            "customer_code": "",
            "address": "KHOPOLI MIDC KHOPOLI",
            "city": "Khopoli",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "",
            "gstin": "27AAACT1344F1Z0",
            "pan": "AAACT1344F",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "THE SUPREME INDUSTRIES LTD (KHOPOLI)",
            "address": "KHOPOLI MIDC KHOPOLI",
            "city": "Khopoli",
            "state": "Maharashtra",
            "state_code": "27",
            "pincode": "",
            "gstin": "27AAACT1344F1Z0",
            "pan": "AAACT1344F"
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "2026-03-08",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "",
            "lr_date": "",
            "transporter_name": "Sri Sai Logistics & Shipping",
            "vehicle_number": "MH46 BU 9533",
            "vehicle_type": "",
            "from_location": "ICTPL",
            "to_location": "Khopoli",
            "place_of_dispatch": "ICTPL",
            "place_of_delivery": "Khopoli"
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "",
                "material_code": "",
                "lr_number": "",
                "product_name": "Freight Charges - Transportation of Consignment",
                "description": "Fixed freight charges for transportation of 20' Import container",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "1",
                "uom": "TRIP",
                "unit_price": "11450.00",
                "gross_amount": "11450.00",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "11450.00",
                "gst_rate": "18",
                "cgst_rate": "9",
                "cgst_amount": "1030.50",
                "sgst_rate": "9",
                "sgst_amount": "1030.50",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": "11450.00"
            }
        ],
        "additional_charges": [
            {
                "description": "Weighment Charges Receivable",
                "charge_type": "Weighment",
                "quantity": "",
                "rate": "",
                "amount": "300.00",
                "taxable_value": "300.00",
                "gst_rate": "18",
                "cgst_amount": "27.00",
                "sgst_amount": "27.00",
                "igst_amount": "",
                "total_amount": "354.00"
            },
            {
                "description": "Unloading Charges Receivable",
                "charge_type": "Unloading",
                "quantity": "",
                "rate": "",
                "amount": "2966.00",
                "taxable_value": "2966.00",
                "gst_rate": "18",
                "cgst_amount": "266.94",
                "sgst_amount": "266.94",
                "igst_amount": "",
                "total_amount": "3499.88"
            },
            {
                "description": "Detention Charges Receivable",
                "charge_type": "Detention",
                "quantity": "",
                "rate": "",
                "amount": "1500.00",
                "taxable_value": "1500.00",
                "gst_rate": "18",
                "cgst_amount": "135.00",
                "sgst_amount": "135.00",
                "igst_amount": "",
                "total_amount": "1770.00"
            }
        ],
        "tax": {
            "taxable_amount": "16216.00",
            "cgst_rate": "9",
            "cgst_amount": "1459.44",
            "sgst_rate": "9",
            "sgst_amount": "1459.44",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": "2918.88"
        },
        "amounts": {
            "subtotal": "16216.00",
            "gross_amount": "16216.00",
            "total_discount": "",
            "freight": "11450.00",
            "transportation_charges": "11450.00",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "2966.00",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "1800.00",
            "taxable_amount": "16216.00",
            "total_tax": "2918.88",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "19134.88",
            "amount_paid": "",
            "balance_due": "19134.88",
            "amount_in_words": "Nineteen Thousand One Hundred Thirty Four and Eighty Eight paise Only"
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "RTGS/NEFT",
            "bank_name": "HDFC BANK LTD.",
            "bank_account_number": "02562320000352",
            "ifsc_code": "HDFC0000256",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "MH46 BU 9533",
            "vehicle_type": "",
            "container_number": "OOLU 1641407",
            "container_type": "20' Import",
            "container_details": "20' Import Container",
            "weight": "17.32",
            "weight_unit": "MT",
            "freight_amount": "11450.00",
            "detention_charges": "1500.00",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "2966.00",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "27AAHFK5419N1ZV",
            "customer_gstin": "27AAACT1344F1Z0",
            "place_of_supply": "Maharashtra",
            "place_of_supply_state_code": "27",
            "reverse_charge": "No",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "16216.00",
            "cgst": "1459.44",
            "sgst": "1459.44",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [],
            "eway_bill_numbers": [],
            "container_numbers": [
                "OOLU 1641407"
            ],
            "vehicle_numbers": [
                "MH46 BU 9533"
            ],
            "other_reference_numbers": [
                "FILE NO. 4600009327-3 BLR",
                "5130002127"
            ]
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "Mani",
            "receiver_signature_present": "Yes",
            "supplier_signature_present": "Yes",
            "company_stamp_present": "Yes"
        },
        "metadata": {
            "page_type": "Original",
            "language": "English",
            "handwritten_content_present": "Yes",
            "stamp_present": "Yes",
            "signature_present": "Yes",
            "qr_code_present": "No",
            "barcode_present": "No"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "00016/26-27",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "27AAHFK5419N1ZV",
            "BASE_VALUE": "16216.00",
            "IGST": "",
            "CGST": "1459.44",
            "SGST": "1459.44",
            "GROSS_TOTAL": "19134.88",
            "INVOICE_DATE": "2026-04-06",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "AAHFK5419N",
            "CUSTOMER_PAN_NO": "AAACT1344F",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "Freight Charges - Transportation of 20' Import Container (Vehicle MH46 BU 9533, Container OOLU 1641407)",
                    "HSN": "",
                    "QTY": "1",
                    "UNIT_PRICE": "11450.00",
                    "AMOUNT": "11450.00"
                },
                {
                    "DESCRIPTION": "Weighment Charges Receivable",
                    "HSN": "",
                    "QTY": "",
                    "UNIT_PRICE": "",
                    "AMOUNT": "300.00"
                },
                {
                    "DESCRIPTION": "Unloading Charges Receivable",
                    "HSN": "",
                    "QTY": "",
                    "UNIT_PRICE": "",
                    "AMOUNT": "2966.00"
                },
                {
                    "DESCRIPTION": "Detention Charges Receivable",
                    "HSN": "",
                    "QTY": "",
                    "UNIT_PRICE": "",
                    "AMOUNT": "1500.00"
                }
            ]
        }
    },
    {
        "document": {
            "document_type": "Delivery Order",
            "document_title": "Delivery Order / Delivery Receipt",
            "invoice_number": "3477",
            "invoice_date": "",
            "invoice_reference_number": "11/17",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "",
            "place_of_supply": "",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "PROTOCOL LOGISTICS PVT. LTD.",
            "legal_name": "PROTOCOL LOGISTICS PVT. LTD.",
            "trade_name": "",
            "vendor_code": "3477",
            "address": "L Wing, 2nd Floor, Akshar Business Park, Next to Container Corporation Of India, Sector 25, Vashi, Navi Mumbai-400 705, Maharashtra",
            "city": "Navi Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "400705",
            "gstin": "",
            "pan": "AAACE3517D",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "",
            "website": ""
        },
        "customer": {
            "name": "",
            "legal_name": "",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "T 11702",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "3477",
            "delivery_order_date": "",
            "delivery_note_number": "11/17",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "11/17",
            "lr_date": "",
            "transporter_name": "",
            "vehicle_number": "",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "Navi Mumbai, Maharashtra",
            "place_of_delivery": ""
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "",
                "material_code": "",
                "lr_number": "11/17",
                "product_name": "",
                "description": "Goods (handwritten description, not clearly legible)",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "2",
                "uom": "Pkgs",
                "unit_price": "",
                "gross_amount": "",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": ""
            }
        ],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "",
            "amount_paid": "",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "",
            "vehicle_type": "",
            "container_number": "",
            "container_type": "",
            "container_details": "",
            "weight": "",
            "weight_unit": "",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "",
            "customer_gstin": "",
            "place_of_supply": "Maharashtra",
            "place_of_supply_state_code": "27",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [
                "3477"
            ],
            "delivery_note_numbers": [
                "11/17"
            ],
            "challan_numbers": [],
            "lr_numbers": [
                "11/17"
            ],
            "eway_bill_numbers": [],
            "container_numbers": [],
            "vehicle_numbers": [],
            "other_reference_numbers": [
                "4181689/02",
                "AAACE3517D"
            ]
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "",
            "receiver_signature_present": "Yes",
            "supplier_signature_present": "Yes",
            "company_stamp_present": "Yes"
        },
        "metadata": {
            "page_type": "Single page - printed form with handwritten entries",
            "language": "English",
            "handwritten_content_present": "Yes",
            "stamp_present": "Yes",
            "signature_present": "Yes",
            "qr_code_present": "No",
            "barcode_present": "No"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "3477",
            "ORDER_NUMBER": "11/17",
            "VENDOR_GST_NO": "",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "",
            "INVOICE_DATE": "",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "AAACE3517D",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "Goods (handwritten, not clearly legible)",
                    "HSN": "",
                    "QTY": "2",
                    "UNIT_PRICE": "",
                    "AMOUNT": ""
                }
            ]
        }
    },
    {
        "document": {
            "document_type": "Invoice",
            "document_title": "Tax Invoice",
            "invoice_number": "1122",
            "invoice_date": "2015-06-23",
            "invoice_reference_number": "",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "INR",
            "place_of_supply": "Andhra Pradesh",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "The Supreme Industries Ltd.",
            "legal_name": "The Supreme Industries Ltd.",
            "trade_name": "The Supreme Industries Ltd.",
            "vendor_code": "",
            "address": "Plot No 1 to 84/A, Survey No 323, Mela Kothanur Village, Kuthambakkam, 488A Sri Krishna Bazzar Street, 6/1/26 to 5/1/2 Dist. S. V. Puram",
            "city": "S. V. Puram",
            "state": "Andhra Pradesh",
            "state_code": "37",
            "country": "India",
            "pincode": "517588",
            "gstin": "37AAACS7024Q1ZD",
            "pan": "AAACS7024Q",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "",
            "website": ""
        },
        "customer": {
            "name": "",
            "legal_name": "",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "",
            "lr_date": "",
            "transporter_name": "",
            "vehicle_number": "",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "",
            "place_of_delivery": ""
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "",
                "material_code": "",
                "lr_number": "",
                "product_name": "",
                "description": "",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "12320",
                "uom": "Kgs",
                "unit_price": "",
                "gross_amount": "163120",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": "163120"
            }
        ],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "163120",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "163120",
            "amount_paid": "",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "",
            "vehicle_type": "",
            "container_number": "",
            "container_type": "",
            "container_details": "",
            "weight": "12320",
            "weight_unit": "Kgs",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "37AAACS7024Q1ZD",
            "customer_gstin": "",
            "place_of_supply": "Andhra Pradesh",
            "place_of_supply_state_code": "37",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [],
            "eway_bill_numbers": [],
            "container_numbers": [],
            "vehicle_numbers": [],
            "other_reference_numbers": [
                "1122"
            ]
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "",
            "receiver_signature_present": "",
            "supplier_signature_present": "yes",
            "company_stamp_present": "yes"
        },
        "metadata": {
            "page_type": "invoice",
            "language": "English",
            "handwritten_content_present": "yes",
            "stamp_present": "yes",
            "signature_present": "yes",
            "qr_code_present": "no",
            "barcode_present": "no"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "1122",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "37AAACS7024Q1ZD",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "163120",
            "INVOICE_DATE": "2015-06-23",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "AAACS7024Q",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "",
                    "HSN": "",
                    "QTY": "12320",
                    "UNIT_PRICE": "",
                    "AMOUNT": "163120"
                }
            ]
        }
    },
    {
        "document": {
            "document_type": "Consignment Note / Lorry Receipt",
            "document_title": "CONSIGNMENT NOTE",
            "invoice_number": "2526-19952",
            "invoice_date": "2026-03-07",
            "invoice_reference_number": "7698268",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "INR",
            "place_of_supply": "Khopoli, Maharashtra",
            "supply_type": "Service - Transportation",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "Kunal Logistics",
            "legal_name": "Kunal Logistics",
            "trade_name": "Kunal Logistics",
            "vendor_code": "",
            "address": "Plot No. 860, Steel Market, Kalamboli, Navi Mumbai - 410 218",
            "city": "Navi Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "410218",
            "gstin": "27AAHFK5419N1ZV",
            "pan": "AAHFK5419N",
            "cin": "",
            "tan": "",
            "email": "kunallogistics@gmail.com",
            "phone": "9324979597",
            "website": "www.kunallogistics.com"
        },
        "customer": {
            "name": "The Supreme Industries Limited (Khopoli) Old",
            "legal_name": "The Supreme Industries Limited",
            "customer_code": "",
            "address": "Village Honad, Taluka Khalapur, Khopoli, Dist Raigad, Maharashtra - 410203",
            "city": "Khopoli",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "410203",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "BLR Supply Chain Pvt Ltd",
            "address": "D201, Lotus Corporate Park, Off W E Highway, Goregaon (E) Mumbai - 400063",
            "city": "Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "pincode": "400063",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "The Supreme Industries Limited (Khopoli) Old",
            "address": "Village Honad, Taluka Khalapur, Khopoli, Dist Raigad",
            "city": "Khopoli",
            "state": "Maharashtra",
            "state_code": "27",
            "pincode": "410203",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "2526-19952",
            "delivery_note_date": "2026-03-07",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "2026-03-07",
            "delivery_date": "2026-03-09",
            "eway_bill_number": "2021 5487 8894",
            "lr_number": "2526-19952",
            "lr_date": "2026-03-07",
            "transporter_name": "Kunal Logistics",
            "vehicle_number": "MH46 BU 9533",
            "vehicle_type": "Container Truck",
            "from_location": "ICTPI",
            "to_location": "Khopoli",
            "place_of_dispatch": "Mumbai (ICTPI)",
            "place_of_delivery": "Khopoli"
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "",
                "material_code": "",
                "lr_number": "2526-19952",
                "product_name": "WHITE MASTERBATCH",
                "description": "ICTPL To Khopoli - White Masterbatch",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "20",
                "uom": "Container (20')",
                "unit_price": "",
                "gross_amount": "",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": ""
            }
        ],
        "additional_charges": [
            {
                "description": "Freight/Transportation Charges",
                "charge_type": "Freight",
                "quantity": "",
                "rate": "",
                "amount": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_amount": "",
                "sgst_amount": "",
                "igst_amount": "",
                "total_amount": ""
            }
        ],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "",
            "amount_paid": "TO BE BILLED",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "TO BE BILLED",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "MH46 BU 9533",
            "vehicle_type": "Container Truck (20')",
            "container_number": "OOLU 1641407",
            "container_type": "20' Standard Container",
            "container_details": "1X20LOT 17280GW",
            "weight": "17.32",
            "weight_unit": "Metric Tons",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "27AAHFK5419N1ZV",
            "customer_gstin": "",
            "place_of_supply": "Khopoli, Maharashtra",
            "place_of_supply_state_code": "27",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "2021 5487 8894",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [
                "2526-19952"
            ],
            "challan_numbers": [],
            "lr_numbers": [
                "2526-19952"
            ],
            "eway_bill_numbers": [
                "2021 5487 8894"
            ],
            "container_numbers": [
                "OOLU 1641407"
            ],
            "vehicle_numbers": [
                "MH46 BU 9533"
            ],
            "other_reference_numbers": [
                "7698268",
                "46000009327-3",
                "FILE NO. 46000009327 - 3",
                "KLD015"
            ]
        },
        "approval": {
            "authorized_signatory_name": "Nawab Ali",
            "receiver_name": "The Supreme Industries Ltd.",
            "receiver_signature_present": "Yes",
            "supplier_signature_present": "Yes",
            "company_stamp_present": "Yes"
        },
        "metadata": {
            "page_type": "Single",
            "language": "English",
            "handwritten_content_present": "Yes",
            "stamp_present": "Yes",
            "signature_present": "Yes",
            "qr_code_present": "No",
            "barcode_present": "No"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "2526-19952",
            "ORDER_NUMBER": "7698268",
            "VENDOR_GST_NO": "27AAHFK5419N1ZV",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "",
            "INVOICE_DATE": "2026-03-07",
            "ORDER_DATE": "2026-02-23",
            "VENDOR_PAN_NO": "AAHFK5419N",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "White Masterbatch (ICTPL To Khopoli)",
                    "HSN": "",
                    "QTY": "20",
                    "UNIT_PRICE": "",
                    "AMOUNT": ""
                }
            ]
        }
    },
    {
        "document": {
            "document_type": "Delivery Receipt",
            "document_title": "",
            "invoice_number": "",
            "invoice_date": "2016-02-07",
            "invoice_reference_number": "",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "",
            "place_of_supply": "",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "THE SUPREME INDUSTRIES LTD.",
            "legal_name": "THE SUPREME INDUSTRIES LTD.",
            "trade_name": "",
            "vendor_code": "",
            "address": "HOMO, KANPUR",
            "city": "KANPUR",
            "state": "",
            "state_code": "",
            "country": "India",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "",
            "website": ""
        },
        "customer": {
            "name": "",
            "legal_name": "",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "2016-02-07",
            "eway_bill_number": "",
            "lr_number": "1123",
            "lr_date": "",
            "transporter_name": "",
            "vehicle_number": "MR46 AV 9533",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "",
            "place_of_delivery": ""
        },
        "items": [],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "1280",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "1280",
            "amount_paid": "",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "MR46 AV 9533",
            "vehicle_type": "",
            "container_number": "",
            "container_type": "",
            "container_details": "",
            "weight": "",
            "weight_unit": "",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "",
            "customer_gstin": "",
            "place_of_supply": "",
            "place_of_supply_state_code": "",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [
                "1123"
            ],
            "eway_bill_numbers": [],
            "container_numbers": [],
            "vehicle_numbers": [
                "MR46 AV 9533"
            ],
            "other_reference_numbers": []
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "",
            "receiver_signature_present": "",
            "supplier_signature_present": "Yes",
            "company_stamp_present": ""
        },
        "metadata": {
            "page_type": "Delivery Note",
            "language": "English",
            "handwritten_content_present": "Yes",
            "stamp_present": "Yes",
            "signature_present": "Yes",
            "qr_code_present": "",
            "barcode_present": ""
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "1280",
            "INVOICE_DATE": "2016-02-07",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": []
        }
    },
    {
        "document": {
            "document_type": "Weighbridge Receipt",
            "document_title": "NIRBHAY FULLY COMPUTERISED WEIGH BRIDGE - Weight Slip",
            "invoice_number": "8762",
            "invoice_date": "2026-03-08",
            "invoice_reference_number": "8763",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "INR",
            "place_of_supply": "Raigad, Maharashtra",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "NIRBHAY FULLY COMPUTERISED WEIGH BRIDGE",
            "legal_name": "NIRBHAY WEIGH BRIDGE",
            "trade_name": "NIRBHAY FULLY COMPUTERISED WEIGH BRIDGE",
            "vendor_code": "",
            "address": "Survey No. 4/18, N.H. 4B, Dhulum (J.N.P.T. Road), Opp. Jiva Yard, Oil Tank Side",
            "city": "Raigad",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "410206",
            "gstin": "",
            "pan": "",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "9769899977",
            "website": ""
        },
        "customer": {
            "name": "KUNAL LOGISTIC",
            "legal_name": "KUNAL LOGISTIC",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "India",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "KUNAL LOGISTIC",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "",
            "lr_date": "",
            "transporter_name": "",
            "vehicle_number": "MH-43-BL-9875",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "",
            "place_of_delivery": ""
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "",
                "material_code": "",
                "lr_number": "",
                "product_name": "Weighbridge Service",
                "description": "Weight measurement for vehicle MH-43-BL-9875 - EMPTY (Tare 12.30 T, Gross 24.70 T, Net 12.40 T)",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "12.40",
                "uom": "Tons",
                "unit_price": "",
                "gross_amount": "24.70",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": "366"
            }
        ],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "24.70",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "366",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "366",
            "amount_paid": "366",
            "balance_due": "0",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "Cash on receipt",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "Cash",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "MH-43-BL-9875",
            "vehicle_type": "Trailer",
            "container_number": "",
            "container_type": "",
            "container_details": "",
            "weight": "12.40",
            "weight_unit": "Tons",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "",
            "customer_gstin": "",
            "place_of_supply": "Raigad, Maharashtra",
            "place_of_supply_state_code": "27",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [],
            "eway_bill_numbers": [],
            "container_numbers": [],
            "vehicle_numbers": [
                "MH-43-BL-9875"
            ],
            "other_reference_numbers": [
                "8762",
                "8763"
            ]
        },
        "approval": {
            "authorized_signatory_name": "NIRBHAY WB",
            "receiver_name": "KUNAL LOGISTIC",
            "receiver_signature_present": "",
            "supplier_signature_present": "",
            "company_stamp_present": "No"
        },
        "metadata": {
            "page_type": "Weighbridge Receipt (Duplicate Copy)",
            "language": "English",
            "handwritten_content_present": "Yes",
            "stamp_present": "No",
            "signature_present": "No",
            "qr_code_present": "No",
            "barcode_present": "No"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "8762",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "366",
            "INVOICE_DATE": "2026-03-08",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "Weighbridge Service - Vehicle MH-43-BL-9875 (Empty)",
                    "HSN": "",
                    "QTY": "12.40",
                    "UNIT_PRICE": "",
                    "AMOUNT": "366"
                }
            ]
        }
    },
    {
        "document": {
            "document_type": "",
            "document_title": "",
            "invoice_number": "",
            "invoice_date": "",
            "invoice_reference_number": "",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "",
            "place_of_supply": "",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "",
            "legal_name": "",
            "trade_name": "",
            "vendor_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "",
            "website": ""
        },
        "customer": {
            "name": "",
            "legal_name": "",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "",
            "lr_date": "",
            "transporter_name": "",
            "vehicle_number": "",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "",
            "place_of_delivery": ""
        },
        "items": [],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "",
            "amount_paid": "",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "",
            "vehicle_type": "",
            "container_number": "",
            "container_type": "",
            "container_details": "",
            "weight": "",
            "weight_unit": "",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "",
            "customer_gstin": "",
            "place_of_supply": "",
            "place_of_supply_state_code": "",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [],
            "eway_bill_numbers": [],
            "container_numbers": [],
            "vehicle_numbers": [],
            "other_reference_numbers": []
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "",
            "receiver_signature_present": "",
            "supplier_signature_present": "",
            "company_stamp_present": ""
        },
        "metadata": {
            "page_type": "blank",
            "language": "",
            "handwritten_content_present": "",
            "stamp_present": "",
            "signature_present": "",
            "qr_code_present": "",
            "barcode_present": ""
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "",
            "INVOICE_DATE": "",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": []
        }
    },
    {
        "document": {
            "document_type": "Tax Invoice cum Receipt",
            "document_title": "Tax Invoice cum Receipt",
            "invoice_number": "SDI/25-26/00374",
            "invoice_date": "2026-03-10",
            "invoice_reference_number": "",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "INR",
            "place_of_supply": "Maharashtra",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "SRI SAI LOGISTICS AND SHIPPING",
            "legal_name": "SRI SAI LOGISTICS AND SHIPPING",
            "trade_name": "SRI SAI Logistics & Shipping",
            "vendor_code": "",
            "address": "SHOP NO 131, AGGARWAL TRADE CENTER, PLOT NO 62, SECTOR 11, CBD Belapur, Navi Mumbai, Raigad",
            "city": "Navi Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "400614",
            "gstin": "27ACPFS8200D1Z3",
            "pan": "ACPFS8200D",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "7738054022",
            "website": ""
        },
        "customer": {
            "name": "KUNAL LOGISTICS",
            "legal_name": "KUNAL LOGISTICS",
            "customer_code": "",
            "address": "PLOT NO.860, STEEL MARKET, NEXT TO MARUTI CHAMBERS, KALAMBOLI, NAVI MUMBAI, Mumbai Suburban",
            "city": "Navi Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "country": "India",
            "pincode": "410218",
            "gstin": "27AAHFK5419N1ZV",
            "pan": "AAHFK5419N",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "KUNAL LOGISTICS",
            "address": "PLOT NO.860, STEEL MARKET, NEXT TO MARUTI CHAMBERS, KALAMBOLI, NAVI MUMBAI, Mumbai Suburban",
            "city": "Navi Mumbai",
            "state": "Maharashtra",
            "state_code": "27",
            "pincode": "410218",
            "gstin": "27AAHFK5419N1ZV",
            "pan": "AAHFK5419N"
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "",
            "lr_date": "",
            "transporter_name": "THE FREIGHTERS LINE",
            "vehicle_number": "",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "",
            "place_of_delivery": ""
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "OOLU1641407",
                "material_code": "",
                "lr_number": "",
                "product_name": "Container Service - 20DV",
                "description": "Container OOLU1641407, Size 20DV, Line: THE FREIGHTERS LINE, InDate 2026-03-10 18:49",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "1",
                "uom": "",
                "unit_price": "",
                "gross_amount": "",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "2966.10",
                "gst_rate": "18",
                "cgst_rate": "9",
                "cgst_amount": "266.95",
                "sgst_rate": "9",
                "sgst_amount": "266.95",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": "3500.00"
            }
        ],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "2966.10",
            "cgst_rate": "9",
            "cgst_amount": "266.95",
            "sgst_rate": "9",
            "sgst_amount": "266.95",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": "533.90"
        },
        "amounts": {
            "subtotal": "2966.10",
            "gross_amount": "2966.10",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "2966.10",
            "total_tax": "533.90",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "3500.00",
            "amount_paid": "3500.00",
            "balance_due": "0.00",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "Other Online Payment",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "",
            "vehicle_type": "",
            "container_number": "OOLU1641407",
            "container_type": "20DV",
            "container_details": "20DV - THE FREIGHTERS LINE",
            "weight": "",
            "weight_unit": "",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "27ACPFS8200D1Z3",
            "customer_gstin": "27AAHFK5419N1ZV",
            "place_of_supply": "Maharashtra",
            "place_of_supply_state_code": "27",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "2966.10",
            "cgst": "266.95",
            "sgst": "266.95",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [],
            "eway_bill_numbers": [],
            "container_numbers": [
                "OOLU1641407"
            ],
            "vehicle_numbers": [],
            "other_reference_numbers": [
                "573980080776"
            ]
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "",
            "receiver_signature_present": "",
            "supplier_signature_present": "",
            "company_stamp_present": ""
        },
        "metadata": {
            "page_type": "Tax Invoice cum Receipt",
            "language": "English",
            "handwritten_content_present": "No",
            "stamp_present": "No",
            "signature_present": "No",
            "qr_code_present": "No",
            "barcode_present": "No"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "SDI/25-26/00374",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "27ACPFS8200D1Z3",
            "BASE_VALUE": "2966.10",
            "IGST": "",
            "CGST": "266.95",
            "SGST": "266.95",
            "GROSS_TOTAL": "3500.00",
            "INVOICE_DATE": "2026-03-10",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "ACPFS8200D",
            "CUSTOMER_PAN_NO": "AAHFK5419N",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "Container OOLU1641407, Size 20DV, Line: THE FREIGHTERS LINE, InDate 2026-03-10 18:49",
                    "HSN": "",
                    "QTY": "1",
                    "UNIT_PRICE": "",
                    "AMOUNT": "2966.10"
                }
            ]
        }
    },
    {
        "document": {
            "document_type": "",
            "document_title": "",
            "invoice_number": "",
            "invoice_date": "",
            "invoice_reference_number": "",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "",
            "place_of_supply": "",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "",
            "legal_name": "",
            "trade_name": "",
            "vendor_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "cin": "",
            "tan": "",
            "email": "",
            "phone": "",
            "website": ""
        },
        "customer": {
            "name": "",
            "legal_name": "",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "",
            "lr_date": "",
            "transporter_name": "",
            "vehicle_number": "",
            "vehicle_type": "",
            "from_location": "",
            "to_location": "",
            "place_of_dispatch": "",
            "place_of_delivery": ""
        },
        "items": [],
        "additional_charges": [],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "",
            "amount_paid": "",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "",
            "vehicle_type": "",
            "container_number": "",
            "container_type": "",
            "container_details": "",
            "weight": "",
            "weight_unit": "",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "",
            "customer_gstin": "",
            "place_of_supply": "",
            "place_of_supply_state_code": "",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [],
            "eway_bill_numbers": [],
            "container_numbers": [],
            "vehicle_numbers": [],
            "other_reference_numbers": []
        },
        "approval": {
            "authorized_signatory_name": "",
            "receiver_name": "",
            "receiver_signature_present": "",
            "supplier_signature_present": "",
            "company_stamp_present": ""
        },
        "metadata": {
            "page_type": "",
            "language": "",
            "handwritten_content_present": "Yes",
            "stamp_present": "",
            "signature_present": "",
            "qr_code_present": "",
            "barcode_present": ""
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "",
            "INVOICE_DATE": "",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": []
        }
    },
    {
        "document": {
            "document_type": "Detention Report",
            "document_title": "DETENTION FOR FACTORY From Jan-26, FY 25-26",
            "invoice_number": "",
            "invoice_date": "",
            "invoice_reference_number": "",
            "original_invoice_number": "",
            "revision_number": "",
            "currency": "",
            "place_of_supply": "",
            "supply_type": "",
            "reverse_charge": ""
        },
        "supplier": {
            "name": "Kumal Logistics",
            "legal_name": "Kumal Logistics",
            "trade_name": "Kumal Logistics",
            "vendor_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "India",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "cin": "",
            "tan": "",
            "email": "kunal.logistics@gmail.com",
            "phone": "",
            "website": ""
        },
        "customer": {
            "name": "The Supreme Industries Limited",
            "legal_name": "The Supreme Industries Limited",
            "customer_code": "",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "country": "India",
            "pincode": "",
            "gstin": "",
            "pan": "",
            "email": "",
            "phone": ""
        },
        "bill_to": {
            "name": "The Supreme Industries Limited",
            "address": "",
            "city": "",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "ship_to": {
            "name": "",
            "address": "",
            "city": "KHOPOLI",
            "state": "",
            "state_code": "",
            "pincode": "",
            "gstin": "",
            "pan": ""
        },
        "purchase_order": {
            "po_number": "",
            "po_date": "",
            "purchase_order_reference": "",
            "purchase_requisition_number": "",
            "contract_number": "",
            "agreement_number": "",
            "work_order_number": ""
        },
        "delivery": {
            "delivery_order_number": "",
            "delivery_order_date": "",
            "delivery_note_number": "",
            "delivery_note_date": "",
            "challan_number": "",
            "challan_date": "",
            "dispatch_date": "",
            "delivery_date": "",
            "eway_bill_number": "",
            "lr_number": "2526-19952",
            "lr_date": "",
            "transporter_name": "Kumal Logistics",
            "vehicle_number": "MH46 BU 9533",
            "vehicle_type": "",
            "from_location": "ICTPL",
            "to_location": "KHOPOLI",
            "place_of_dispatch": "ICTPL",
            "place_of_delivery": "KHOPOLI"
        },
        "items": [
            {
                "line_number": "1",
                "item_code": "",
                "material_code": "",
                "lr_number": "2526-19952",
                "product_name": "Container Transportation - The Supreme Industries Limited",
                "description": "LR 2526-19952, Vehicle MH46 BU 9533, Container OOLU 1641407, From ICTPL to KHOPOLI, Empty yard detention 1 DAY OK (Container Damage), Factory detention from 08-03-2026 to 09-03-2026",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "1",
                "uom": "TRIP",
                "unit_price": "",
                "gross_amount": "",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": ""
            },
            {
                "line_number": "2",
                "item_code": "",
                "material_code": "",
                "lr_number": "2526-20188",
                "product_name": "Container Transportation - The Supreme Industries Limited",
                "description": "LR 2526-20188, Vehicle MH46 BF 4333, Container MRSU 5111390, From ICTPL to KHOPOLI, Factory detention 1 DAY OK 15-03-2026, Reason Local vehicle Unloading, Empty yard detention 0",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "1",
                "uom": "TRIP",
                "unit_price": "",
                "gross_amount": "",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": ""
            },
            {
                "line_number": "3",
                "item_code": "",
                "material_code": "",
                "lr_number": "2526-20187",
                "product_name": "Container Transportation - The Supreme Industries Limited",
                "description": "LR 2526-20187, Vehicle MH46 CL 1172, Container DPWU 2082951, From ICTPL to KHOPOLI, Factory detention 1 DAY OK 15-03-2026, Reason Local vehicle Unloading, Empty yard detention 0",
                "hsn_code": "",
                "sac_code": "",
                "quantity": "1",
                "uom": "TRIP",
                "unit_price": "",
                "gross_amount": "",
                "discount": "",
                "discount_percentage": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_rate": "",
                "cgst_amount": "",
                "sgst_rate": "",
                "sgst_amount": "",
                "igst_rate": "",
                "igst_amount": "",
                "utgst_rate": "",
                "utgst_amount": "",
                "cess_rate": "",
                "cess_amount": "",
                "other_charges": "",
                "line_total": ""
            }
        ],
        "additional_charges": [
            {
                "description": "Factory Detention - LR 2526-19952",
                "charge_type": "Factory Detention",
                "quantity": "1",
                "rate": "",
                "amount": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_amount": "",
                "sgst_amount": "",
                "igst_amount": "",
                "total_amount": ""
            },
            {
                "description": "Factory Detention - LR 2526-20188",
                "charge_type": "Factory Detention",
                "quantity": "1",
                "rate": "",
                "amount": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_amount": "",
                "sgst_amount": "",
                "igst_amount": "",
                "total_amount": ""
            },
            {
                "description": "Factory Detention - LR 2526-20187",
                "charge_type": "Factory Detention",
                "quantity": "1",
                "rate": "",
                "amount": "",
                "taxable_value": "",
                "gst_rate": "",
                "cgst_amount": "",
                "sgst_amount": "",
                "igst_amount": "",
                "total_amount": ""
            }
        ],
        "tax": {
            "taxable_amount": "",
            "cgst_rate": "",
            "cgst_amount": "",
            "sgst_rate": "",
            "sgst_amount": "",
            "igst_rate": "",
            "igst_amount": "",
            "utgst_rate": "",
            "utgst_amount": "",
            "cess_rate": "",
            "cess_amount": "",
            "other_tax": "",
            "total_tax": ""
        },
        "amounts": {
            "subtotal": "",
            "gross_amount": "",
            "total_discount": "",
            "freight": "",
            "transportation_charges": "",
            "packing_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "insurance_charges": "",
            "handling_charges": "",
            "other_charges": "",
            "taxable_amount": "",
            "total_tax": "",
            "round_off": "",
            "advance_paid": "",
            "total_amount": "",
            "amount_paid": "",
            "balance_due": "",
            "amount_in_words": ""
        },
        "payment": {
            "payment_terms": "",
            "due_date": "",
            "credit_period_days": "",
            "payment_method": "",
            "bank_name": "",
            "bank_account_number": "",
            "ifsc_code": "",
            "upi_id": ""
        },
        "logistics": {
            "vehicle_number": "MH46 BU 9533, MH46 BF 4333, MH46 CL 1172",
            "vehicle_type": "",
            "container_number": "OOLU 1641407, MRSU 5111390, DPWU 2082951",
            "container_type": "",
            "container_details": "OOLU 1641407, MRSU 5111390, DPWU 2082951",
            "weight": "",
            "weight_unit": "",
            "freight_amount": "",
            "detention_charges": "",
            "demurrage_charges": "",
            "parking_charges": "",
            "loading_charges": "",
            "unloading_charges": "",
            "empty_unloading_charges": ""
        },
        "gst_compliance": {
            "supplier_gstin": "",
            "customer_gstin": "",
            "place_of_supply": "",
            "place_of_supply_state_code": "",
            "reverse_charge": "",
            "irn": "",
            "acknowledgement_number": "",
            "acknowledgement_date": "",
            "qr_code_data": "",
            "eway_bill_number": "",
            "gst_taxable_value": "",
            "cgst": "",
            "sgst": "",
            "igst": "",
            "utgst": "",
            "cess": ""
        },
        "references": {
            "po_numbers": [],
            "sales_order_numbers": [],
            "delivery_order_numbers": [],
            "delivery_note_numbers": [],
            "challan_numbers": [],
            "lr_numbers": [
                "2526-19952",
                "2526-20188",
                "2526-20187"
            ],
            "eway_bill_numbers": [],
            "container_numbers": [
                "OOLU 1641407",
                "MRSU 5111390",
                "DPWU 2082951"
            ],
            "vehicle_numbers": [
                "MH46 BU 9533",
                "MH46 BF 4333",
                "MH46 CL 1172"
            ],
            "other_reference_numbers": [
                "460000009327/3",
                "4600000009289/1",
                "4600000094321/1"
            ]
        },
        "approval": {
            "authorized_signatory_name": "ambuhval Prajapati",
            "receiver_name": "",
            "receiver_signature_present": "No",
            "supplier_signature_present": "No",
            "company_stamp_present": "No"
        },
        "metadata": {
            "page_type": "Email - Detention Report",
            "language": "English",
            "handwritten_content_present": "Yes",
            "stamp_present": "No",
            "signature_present": "No",
            "qr_code_present": "No",
            "barcode_present": "No"
        },
        "required_fields": {
            "IRN_NO": "",
            "IRN_DATE": "",
            "INVOICE_NUMBER": "",
            "ORDER_NUMBER": "",
            "VENDOR_GST_NO": "",
            "BASE_VALUE": "",
            "IGST": "",
            "CGST": "",
            "SGST": "",
            "GROSS_TOTAL": "",
            "INVOICE_DATE": "",
            "ORDER_DATE": "",
            "VENDOR_PAN_NO": "",
            "CUSTOMER_PAN_NO": "",
            "ITEM_LIST": [
                {
                    "DESCRIPTION": "LR 2526-19952 - Container Transportation from ICTPL to KHOPOLI for The Supreme Industries Limited, Vehicle MH46 BU 9533, Container OOLU 1641407, Factory Detention 1 DAY, Reason: Container Damage",
                    "HSN": "",
                    "QTY": "1",
                    "UNIT_PRICE": "",
                    "AMOUNT": ""
                },
                {
                    "DESCRIPTION": "LR 2526-20188 - Container Transportation from ICTPL to KHOPOLI for The Supreme Industries Limited, Vehicle MH46 BF 4333, Container MRSU 5111390, Factory Detention 1 DAY OK, Reason: Local vehicle Unloading",
                    "HSN": "",
                    "QTY": "1",
                    "UNIT_PRICE": "",
                    "AMOUNT": ""
                },
                {
                    "DESCRIPTION": "LR 2526-20187 - Container Transportation from ICTPL to KHOPOLI for The Supreme Industries Limited, Vehicle MH46 CL 1172, Container DPWU 2082951, Factory Detention 1 DAY OK, Reason: Local vehicle Unloading",
                    "HSN": "",
                    "QTY": "1",
                    "UNIT_PRICE": "",
                    "AMOUNT": ""
                }
            ]
        }
    }
]